language: python
python:
- '3.6'
services:
- docker
env:
- TORTUGA_BUILD_DOCKER="true" BUILD_KIT_IMAGE="univa/tortuga-build-kit:master-latest" URB_VER="3.1.1" URB_TAG="v3.1.1_rc1"
before_install:
- docker pull $BUILD_KIT_IMAGE
- cd tortuga_kits/urb_uge_1_0_0/puppet_modules/tortuga_kit_urb_uge/files && curl -sLO https://github.com/UnivaCorporation/urb-uge/releases/download/${URB_TAG}/urb-${URB_VER}.tar.gz && cd -
install:
- chmod -R a-w .
- sudo chown -R travis:travis /home/travis/
- docker run --rm -it -v `pwd`:/kit-src $BUILD_KIT_IMAGE
script:
- echo "Done"
deploy:
  provider: releases
  api_key:
    secure: hzX/F8enyV46TasRtodhreoEQjWD2+PZX2ckQMqgBEMmjH7uQYe2yLcm0JuQqlD524Iz3335o4Cbc0MoIrycZ5A9hQ8TaQpOmR4sK2G0shSCEDdnUxWWU3gqfzlencuCeoklgoNbDXvJtG/1KFEylg6OoWMjy+PTpkDcBFXAjOid1KrnTLbAZsjgQro5gVNQF4W168+Rh39qyq+eghhmMAX+kOkf3vIoXrFvsotblsReCdaffb/6O2ihQvdq2Lo7I1s9ebDFs3pLT9NXhxMkbE1FQwu+7+gIAH11Wk30uZ2RHByAd/f8/DKj0WAUsq2PMXb6RjV3oyxs1ISqWEnJHLn4XrYdyGlvn/vgCfLpK2HmX/2l6DmmvReciAZTUzdNRSRNncfV7D0dDmPIjPg/PSSibyHOTTtm627SROwLZvqef36FpqDXLxOkbZmM68liW/1yF0K+ZS0zUkP9zNcedl6YqOVGcoct8QpuN7K/OZ2HsNVI8Ym1x4gNF3jcmmwKW4Gr+zVZJFgyV47NEWANaouHGNqtny/diGSMGaQbpyVVphowq4GA79mjaV2XrNahBgnE/6puZkaD6FwzvQfdwKeZ/BvzUflJ6pBlJ5uUFvoMY93Y6zF4HqGVQ6+9TMaBdjqR//JsV2xtPTQ82emjkIvodIkwhn+RTBtX3y2T4jo=
  file_glob: true
  file: dist/kit-urb_uge*.tar.bz2
  skip_cleanup: true
  on:
    all_branches: true
#    tags: true
    repo: UnivaCorporation/tortuga-kit-urb-uge
